[tool.poetry]
name = "omega-back"
version = "0.1.0"
description = ""
authors = ["thomas <psychoid@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
djangorestframework = "^3.15.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
