# Generated by Django 5.1.1 on 2024-10-17 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('note', models.TextField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeOrExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('kilo', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('litre', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('supply', models.DateField(auto_now_add=True)),
                ('frequency', models.SmallIntegerField(default=0)),
                ('missing', models.BooleanField(default=False)),
                ('url', models.URLField(default='')),
                ('photo', models.ImageField(default=None, upload_to=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('km', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('url', models.URLField(default='')),
                ('logo', models.ImageField(default=None, upload_to=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('automatically_deducted', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('product', models.ManyToManyField(to='budget.product')),
                ('shop', models.ManyToManyField(to='budget.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('automatically_deducted', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cash', models.BooleanField(default=False)),
                ('start_month', models.SmallIntegerField(choices=[('00', ''), ('01', 'Janvier'), ('02', 'Fevrier'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Aout'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], default='')),
                ('year_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('fee_or_expense', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='budget.feeorexpense')),
                ('tax', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='budget.tax')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
