# Generated by Django 5.1.1 on 2024-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_company_alter_salary_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coast',
            name='product',
        ),
        migrations.RemoveField(
            model_name='coast',
            name='shop',
        ),
        migrations.AlterField(
            model_name='saving',
            name='start_month',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Coast',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
