# Generated by Django 5.1.1 on 2024-11-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_coast_product_remove_coast_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='fee_or_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.feeorexpense'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.tax'),
        ),
    ]
