# Generated by Django 5.1.1 on 2024-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_saving_fee_or_expense_alter_saving_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionalexpense',
            name='note',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
