# Generated by Django 5.1.1 on 2024-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_exceptionalexpense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionalexpense',
            name='note',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
