# Generated by Django 5.1.1 on 2025-04-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('kilo', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('litre', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('supply', models.DateField(auto_now_add=True)),
                ('frequency', models.SmallIntegerField(default=0)),
                ('missing', models.BooleanField(default=False)),
                ('url', models.URLField(default='')),
                ('photo', models.ImageField(default=None, upload_to=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('km', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('url', models.URLField(default='')),
                ('logo', models.ImageField(default=None, upload_to=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product', models.ManyToManyField(to='shop.product')),
                ('shop', models.ManyToManyField(to='shop.shop')),
            ],
        ),
    ]
